// Dataset estático de regiones y comunas de Chile (división administrativa
// vigente, 16 regiones) — usado para los selects encadenados de dirección
// en checkout/Mi Cuenta. No depende de ningún servicio externo.
export const CHILE_REGIONS: { name: string; comunas: string[] }[] = [
  {
    name: "Arica y Parinacota",
    comunas: ["Arica", "Camarones", "Putre", "General Lagos"],
  },
  {
    name: "Tarapacá",
    comunas: ["Iquique", "Alto Hospicio", "Pozo Almonte", "Camiña", "Colchane", "Huara", "Pica"],
  },
  {
    name: "Antofagasta",
    comunas: [
      "Antofagasta",
      "Mejillones",
      "Sierra Gorda",
      "Taltal",
      "Calama",
      "Ollagüe",
      "San Pedro de Atacama",
      "Tocopilla",
      "María Elena",
    ],
  },
  {
    name: "Atacama",
    comunas: ["Copiapó", "Caldera", "Tierra Amarilla", "Chañaral", "Diego de Almagro", "Vallenar", "Alto del Carmen", "Freirina", "Huasco"],
  },
  {
    name: "Coquimbo",
    comunas: [
      "La Serena",
      "Coquimbo",
      "Andacollo",
      "La Higuera",
      "Paihuano",
      "Vicuña",
      "Illapel",
      "Canela",
      "Los Vilos",
      "Salamanca",
      "Ovalle",
      "Combarbalá",
      "Monte Patria",
      "Punitaqui",
      "Río Hurtado",
    ],
  },
  {
    name: "Valparaíso",
    comunas: [
      "Valparaíso",
      "Viña del Mar",
      "Concón",
      "Quintero",
      "Puchuncaví",
      "Casablanca",
      "Juan Fernández",
      "San Antonio",
      "Cartagena",
      "El Tabo",
      "El Quisco",
      "Algarrobo",
      "Santo Domingo",
      "Quillota",
      "La Calera",
      "Hijuelas",
      "La Cruz",
      "Nogales",
      "San Felipe",
      "Los Andes",
      "Quilpué",
      "Villa Alemana",
      "Limache",
      "Olmué",
      "Petorca",
      "La Ligua",
      "Cabildo",
      "Papudo",
      "Zapallar",
      "Isla de Pascua",
    ],
  },
  {
    name: "Metropolitana de Santiago",
    comunas: [
      "Santiago",
      "Cerrillos",
      "Cerro Navia",
      "Conchalí",
      "El Bosque",
      "Estación Central",
      "Huechuraba",
      "Independencia",
      "La Cisterna",
      "La Florida",
      "La Granja",
      "La Pintana",
      "La Reina",
      "Las Condes",
      "Lo Barnechea",
      "Lo Espejo",
      "Lo Prado",
      "Macul",
      "Maipú",
      "Ñuñoa",
      "Pedro Aguirre Cerda",
      "Peñalolén",
      "Providencia",
      "Pudahuel",
      "Quilicura",
      "Quinta Normal",
      "Recoleta",
      "Renca",
      "San Joaquín",
      "San Miguel",
      "San Ramón",
      "Vitacura",
      "Puente Alto",
      "Pirque",
      "San José de Maipo",
      "Colina",
      "Lampa",
      "Til Til",
      "San Bernardo",
      "Buin",
      "Calera de Tango",
      "Paine",
      "Melipilla",
      "Alhué",
      "Curacaví",
      "María Pinto",
      "San Pedro",
      "Talagante",
      "El Monte",
      "Isla de Maipo",
      "Padre Hurtado",
      "Peñaflor",
    ],
  },
  {
    name: "Libertador General Bernardo O'Higgins",
    comunas: [
      "Rancagua",
      "Machalí",
      "Graneros",
      "Codegua",
      "Mostazal",
      "Doñihue",
      "Coltauco",
      "Coinco",
      "Quinta de Tilcoco",
      "Rengo",
      "Requínoa",
      "Olivar",
      "San Vicente",
      "Pichidegua",
      "Peumo",
      "Las Cabras",
      "San Fernando",
      "Chimbarongo",
      "Placilla",
      "Nancagua",
      "Chépica",
      "Santa Cruz",
      "Lolol",
      "Pumanque",
      "Palmilla",
      "Peralillo",
      "Pichilemu",
      "Navidad",
      "Litueche",
      "La Estrella",
      "Marchihue",
      "Paredones",
    ],
  },
  {
    name: "Maule",
    comunas: [
      "Talca",
      "San Clemente",
      "Pelarco",
      "Pencahue",
      "Maule",
      "San Rafael",
      "Río Claro",
      "Curepto",
      "Constitución",
      "Empedrado",
      "Curicó",
      "Teno",
      "Romeral",
      "Molina",
      "Sagrada Familia",
      "Hualañé",
      "Licantén",
      "Vichuquén",
      "Rauco",
      "Linares",
      "Yerbas Buenas",
      "Colbún",
      "Longaví",
      "Parral",
      "Retiro",
      "Villa Alegre",
      "San Javier",
      "Cauquenes",
      "Pelluhue",
      "Chanco",
    ],
  },
  {
    name: "Ñuble",
    comunas: [
      "Chillán",
      "Chillán Viejo",
      "Bulnes",
      "Cobquecura",
      "Coelemu",
      "Coihueco",
      "El Carmen",
      "Ninhue",
      "Ñiquén",
      "Pemuco",
      "Pinto",
      "Portezuelo",
      "Quillón",
      "Quirihue",
      "Ránquil",
      "San Carlos",
      "San Fabián",
      "San Ignacio",
      "San Nicolás",
      "Treguaco",
      "Yungay",
    ],
  },
  {
    name: "Biobío",
    comunas: [
      "Concepción",
      "Talcahuano",
      "San Pedro de la Paz",
      "Chiguayante",
      "Hualpén",
      "Coronel",
      "Lota",
      "Penco",
      "Tomé",
      "Hualqui",
      "Florida",
      "Santa Juana",
      "Los Ángeles",
      "Cabrero",
      "Laja",
      "San Rosendo",
      "Tucapel",
      "Antuco",
      "Quilleco",
      "Santa Bárbara",
      "Quilaco",
      "Mulchén",
      "Negrete",
      "Nacimiento",
      "Yumbel",
      "Alto Biobío",
      "Arauco",
      "Curanilahue",
      "Los Álamos",
      "Cañete",
      "Contulmo",
      "Tirúa",
      "Lebu",
    ],
  },
  {
    name: "La Araucanía",
    comunas: [
      "Temuco",
      "Padre Las Casas",
      "Vilcún",
      "Cunco",
      "Melipeuco",
      "Curarrehue",
      "Pucón",
      "Villarrica",
      "Freire",
      "Pitrufquén",
      "Gorbea",
      "Toltén",
      "Loncoche",
      "Nueva Imperial",
      "Carahue",
      "Saavedra",
      "Teodoro Schmidt",
      "Cholchol",
      "Angol",
      "Renaico",
      "Collipulli",
      "Lonquimay",
      "Curacautín",
      "Victoria",
      "Traiguén",
      "Lumaco",
      "Purén",
      "Los Sauces",
      "Ercilla",
      "Perquenco",
    ],
  },
  {
    name: "Los Ríos",
    comunas: [
      "Valdivia",
      "Mariquina",
      "Lanco",
      "Los Lagos",
      "Máfil",
      "Corral",
      "Paillaco",
      "Panguipulli",
      "La Unión",
      "Río Bueno",
      "Lago Ranco",
      "Futrono",
    ],
  },
  {
    name: "Los Lagos",
    comunas: [
      "Puerto Montt",
      "Puerto Varas",
      "Cochamó",
      "Calbuco",
      "Maullín",
      "Los Muermos",
      "Fresia",
      "Frutillar",
      "Llanquihue",
      "Osorno",
      "San Pablo",
      "Puyehue",
      "Puerto Octay",
      "Purranque",
      "Río Negro",
      "San Juan de la Costa",
      "Castro",
      "Ancud",
      "Quemchi",
      "Dalcahue",
      "Curaco de Vélez",
      "Quinchao",
      "Puqueldón",
      "Chonchi",
      "Queilén",
      "Quellón",
      "Chaitén",
      "Hualaihué",
      "Futaleufú",
      "Palena",
    ],
  },
  {
    name: "Aysén del General Carlos Ibáñez del Campo",
    comunas: [
      "Coyhaique",
      "Lago Verde",
      "Aysén",
      "Cisnes",
      "Guaitecas",
      "Cochrane",
      "O'Higgins",
      "Tortel",
      "Chile Chico",
      "Río Ibáñez",
    ],
  },
  {
    name: "Magallanes y de la Antártica Chilena",
    comunas: [
      "Punta Arenas",
      "Río Verde",
      "Laguna Blanca",
      "San Gregorio",
      "Natales",
      "Torres del Paine",
      "Porvenir",
      "Primavera",
      "Timaukel",
      "Cabo de Hornos",
      "Antártica",
    ],
  },
];

export function getComunasForRegion(regionName: string): string[] {
  return CHILE_REGIONS.find((r) => r.name === regionName)?.comunas ?? [];
}
